%% Copyright 2009, 2010, 2011, 2012, 2013 Anton Lavrik
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%     http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.

-ifndef(__PIQI_TOOLS_HRL__).
-define(__PIQI_TOOLS_HRL__, 1).

% type definitions generated by piqic
-include("piqi_tools_piqi.hrl").


-type piqi_convert_input_format() :: piqi_tools_format().

-type piqi_convert_output_format() :: piqi_tools_format().


% Serialization options to be passed as an argument to * gen_<typename>/3 and
% parse_<typename>/3 functions
%
% pretty_print
%
%      Pretty-print generated JSON and XML output (default = true)
%
% json_omit_null_fields
%
%      Omit missing optional and empty repeated fields from JSON
%      output instead of representing them as {"field_name": null} and
%      {"field_name", []} JSON fields (default = true)
%
% use_strict_parsing
%
%      Treat unknown and duplicate fields as errors when parsing JSON,
%      XML and Piq formats (default = false)
%
-type piqi_convert_option() ::
       'pretty_print'
    | {'pretty_print', boolean()}
    |  'json_omit_null_fields'
    | {'json_omit_null_fields', boolean()}
    |  'use_strict_parsing'
    | {'use_strict_parsing', boolean()}.

% default options are presently set to ['pretty_print', 'json_omit_null_fields']
-type piqi_convert_options() :: [ piqi_convert_option() ].


-endif.
