.PHONY: all dirs clean pre_target post_target

all: pre_target dirs post_target


# Added -j1 to stop parallel makes from blowing up. -ejs
dirs: $(DIRS)
	set -e; \
	for dir in $(DIRS); do \
		$(MAKE) -j1 -C $$dir $(MAKECMDGOALS); \
	done


clean:: dirs


pre_target::
post_target::


# vim:ft=make
