include $(PIQI_ROOT)/make/Makefile.ocaml

RESULT = test


SOURCES = $(PIQI_ML_FILES) test_packed.ml test_packed_array.ml


PIQI_FILES = packed-nocompat.piqi packed.piqi packed-array.piqi

PIQI_ML_FILES = \
	packed_nocompat_piqi.ml \
	packed_piqi.ml \
	packed_array_piqi.ml \


PRE_TARGETS = $(PIQI_ML_FILES)


PIQIC = piqic ocaml
PIQIC_FLAGS = --pp --gen-defaults


PACKS = piqi.runtime

# LIBS = piqirun
# LIBDIRS = $(PIQI_ROOT)/piqirun-ocaml
# INCDIRS = $(PIQI_ROOT)/piqirun-ocaml


all: nc #top


$(PIQI_ML_FILES): $(PIQI_FILES)
	set -e; \
	for i in $^; do \
		$(PIQIC) $(PIQIC_FLAGS) $$i ; \
	done



include $(OCAMLMAKEFILE)
