#!/bin/sh
set -ex

f=$1


# When piqi sees this variable, it prints some extra information on stderr. The
# same effect can be achieved by specifying "--trace" command-line parameter.
#
#export PIQI_TRACE=1

# pretty print to standard output
piqi pp $f.piq


# check piq validity: syntax, then structured validity i.e. type check
piqi check $f.piq


# convert to "piq" encoding and print to stdout. "piq" encoding is used as
# default ouput encoding. Input encoding is determined by file's extension
# unless specified explicitly.
piqi convert $f.piq


# the same as previous command, also add default values to all optional fields
# which are missing in source objects
piqi convert --add-defaults $f.piq

# convert to pib encoding, writing output to "<source file>.pib" file
piqi convert -t pib $f.piq

# convert back to .piq
piqi convert $f.piq.pib

# convert back to .piq and add defaults
piqi convert --add-defaults $f.piq.pib

# convert to json encoding, writing output to "<source file>.json" file
piqi convert -t json $f.piq

# convert back to .piq
piqi convert $f.piq.json

# convert .json to .pib
piqi convert -t pib $f.piq.json

# convert .pib to .json
piqi convert -t json $f.piq.pib

# convert .pib to .xml
piqi convert -t xml $f.piq.pib

# convert .pib to .json; generate "null" for missing optional fields
piqi convert -t json --json-omit-null-fields false $f.piq.pib

#
# Similar to the above but this time, embedding Piqi type specs while
# converting.
#

# the same as previous command, also add default values to all optional fields
# which are missing in source objects
piqi convert --embed-piqi --add-defaults $f.piq


# convert to pib encoding, writing output to "<source file>.pib" file
piqi convert -t pib $f.piq

# convert back to .piq
piqi convert --embed-piqi $f.piq.pib

# convert to pib encoding, writing output to "<source file>.pib" file
piqi convert --embed-piqi -t pib $f.piq

# convert back to .piq
piqi convert $f.piq.pib


# convert to json encoding, writing output to "<source file>.json" file
piqi convert -t json $f.piq

# convert back to .piq
piqi convert --embed-piqi $f.piq.json

# convert to json encoding, writing output to "<source file>.json" file
piqi convert --embed-piqi -t json $f.piq

# convert back to .piq
piqi convert $f.piq.json


# convert .json to .pib
piqi convert -t pib $f.piq.json

# convert .pib back to .json
piqi convert -t json $f.piq.json.pib
