#!/bin/sh

if [ $# -ne 1 ]
then
    echo "Usage: $0 ADDRESS_BOOK_FILE"
    exit 1
fi


RUN="add_person run"
ERL_PATH=$PIQI_ROOT/piqi-erlang/ebin


erl -pa $ERL_PATH -noshell -run $RUN "$0" "$1" -s erlang halt

