#!/bin/sh

if [ $# -ne 1 ]
then
    echo "Usage: $0 ADDRESS_BOOK_FILE"
    exit 1
fi


RUN="io_json_xml_pb run"
ERL_PATH=$PIQI_ROOT/piqi-erlang/ebin


erl -pa $ERL_PATH -noshell -s piqi start -run $RUN "$1" -s erlang halt

