include $(PIQI_ROOT)/make/Makefile.ocaml


RESULT = test


SOURCES = \
	$(PIQI_ML_FILES) \
	test.ml


PACKS = unix piqi.lib


PIQI_FILES = addressbook.proto.piqi piqi.piqi piqi-obj.piqi

PIQI_ML_FILES = \
	addressbook_piqi.ml addressbook_piqi_ext.ml \
	piqi_piqi.ml piqi_piqi_ext.ml \
	piqi_obj_piqi.ml piqi_obj_piqi_ext.ml


PRE_TARGETS = $(PIQI_ML_FILES)


PIQIC = piqic
PIQIC_FLAGS = --pp --no-warnings #--leave-tmp-files


all: native-code #byte-code debug-code


$(PIQI_ML_FILES): $(PIQI_FILES)
	set -e; \
	for i in $^; do \
		$(PIQIC) ocaml-ext $(PIQIC_FLAGS) $$i ; \
	done


clean::
	rm -f *.tmp.ml


include $(OCAMLMAKEFILE)
